/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Michelle
 */
public class CrearPerfil extends javax.swing.JPanel {

    /**
     * Creates new form CrearPerfil
     */
    public CrearPerfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NombreUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Contraseña = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Personalidades = new javax.swing.JComboBox<>();
        TiempoLibre = new javax.swing.JLabel();
        MuchoTiempo = new javax.swing.JRadioButton();
        PocoTiempo = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        Activa = new javax.swing.JRadioButton();
        Sedentaria = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        LugarAmplio = new javax.swing.JRadioButton();
        Piso = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        SiAlergia = new javax.swing.JRadioButton();
        NoAlergias = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        SiNinos = new javax.swing.JRadioButton();
        NoNinios = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        SiMascotas = new javax.swing.JRadioButton();
        NoMascotas = new javax.swing.JRadioButton();
        Registro = new javax.swing.JButton();
        Volver = new javax.swing.JButton();

        jInternalFrame1.setBackground(new java.awt.Color(0, 204, 153));
        jInternalFrame1.setTitle("Crear un nuevo Perfil");
        jInternalFrame1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jInternalFrame1.setName("Crear un nuevo Perfil"); // NOI18N
        jInternalFrame1.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setText("Crear un nuevo Perfil");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Nombre de usuario:");

        NombreUsuario.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Contraseña:");

        Contraseña.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Personalidad");

        Personalidades.setBackground(new java.awt.Color(0, 153, 153));
        Personalidades.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Personalidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activa", "Agresiva", "Amigable", "Antisocial", "Cariñosa", "Guardiana", "Inquieta", "Pasciente", "Simpática", "Social", "Territorial", "Tranquila", "Traviesa", "Vigorosa" }));
        Personalidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PersonalidadesMousePressed(evt);
            }
        });

        TiempoLibre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TiempoLibre.setText("Tiempo libre");

        MuchoTiempo.setBackground(new java.awt.Color(0, 204, 153));
        MuchoTiempo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        MuchoTiempo.setText("Mucho tiempo libre");

        PocoTiempo.setBackground(new java.awt.Color(0, 204, 153));
        PocoTiempo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        PocoTiempo.setText("Poco tiempo libre");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Se considera una persona:");

        Activa.setBackground(new java.awt.Color(0, 204, 153));
        Activa.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Activa.setText("Activa");

        Sedentaria.setBackground(new java.awt.Color(0, 204, 153));
        Sedentaria.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Sedentaria.setText("Sedentaria");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Su vivienda es:");

        LugarAmplio.setBackground(new java.awt.Color(0, 204, 153));
        LugarAmplio.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        LugarAmplio.setText("Lugar amplio");

        Piso.setBackground(new java.awt.Color(0, 204, 153));
        Piso.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Piso.setText("Piso (apartamento)");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Alergias");

        SiAlergia.setBackground(new java.awt.Color(0, 204, 153));
        SiAlergia.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        SiAlergia.setText("Sí");

        NoAlergias.setBackground(new java.awt.Color(0, 204, 153));
        NoAlergias.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        NoAlergias.setText("No");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("Niños");

        SiNinos.setBackground(new java.awt.Color(0, 204, 153));
        SiNinos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        SiNinos.setText("Sí");

        NoNinios.setBackground(new java.awt.Color(0, 204, 153));
        NoNinios.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        NoNinios.setText("No");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setText("Otras mascotas");

        SiMascotas.setBackground(new java.awt.Color(0, 204, 153));
        SiMascotas.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        SiMascotas.setText("Sí");

        NoMascotas.setBackground(new java.awt.Color(0, 204, 153));
        NoMascotas.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        NoMascotas.setText("No");

        Registro.setBackground(new java.awt.Color(255, 153, 0));
        Registro.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Registro.setText("Registrarse");
        Registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegistroMousePressed(evt);
            }
        });

        Volver.setBackground(new java.awt.Color(255, 153, 0));
        Volver.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Volver.setText("Regresar");
        Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VolverMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TiempoLibre)
                                .addGap(98, 98, 98))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Personalidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(Activa)
                                        .addGap(18, 18, 18)
                                        .addComponent(Sedentaria)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(MuchoTiempo)
                                        .addGap(18, 18, 18)
                                        .addComponent(PocoTiempo))
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(LugarAmplio)
                                        .addGap(18, 18, 18)
                                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(Piso)
                                            .addComponent(SiMascotas)
                                            .addComponent(NoMascotas)))))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(84, 84, 84))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Registro)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Volver)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(30, 30, 30))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addComponent(jLabel1)))
                        .addGap(40, 249, Short.MAX_VALUE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(SiAlergia)
                            .addComponent(NoAlergias))
                        .addGap(203, 203, 203)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NoNinios)
                            .addComponent(SiNinos)
                            .addComponent(jLabel8))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TiempoLibre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Personalidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MuchoTiempo)
                    .addComponent(PocoTiempo))
                .addGap(39, 39, 39)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Activa)
                    .addComponent(Sedentaria)
                    .addComponent(LugarAmplio)
                    .addComponent(Piso))
                .addGap(30, 30, 30)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiAlergia)
                    .addComponent(SiNinos)
                    .addComponent(SiMascotas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoAlergias)
                    .addComponent(NoNinios)
                    .addComponent(NoMascotas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Volver)
                    .addComponent(Registro))
                .addGap(26, 26, 26))
        );

        Personalidades.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegistroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistroMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistroMousePressed

    private void VolverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_VolverMousePressed

    private void PersonalidadesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PersonalidadesMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_PersonalidadesMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Activa;
    private javax.swing.JTextField Contraseña;
    private javax.swing.JRadioButton LugarAmplio;
    private javax.swing.JRadioButton MuchoTiempo;
    private javax.swing.JRadioButton NoAlergias;
    private javax.swing.JRadioButton NoMascotas;
    private javax.swing.JRadioButton NoNinios;
    private javax.swing.JTextField NombreUsuario;
    private javax.swing.JComboBox<String> Personalidades;
    private javax.swing.JRadioButton Piso;
    private javax.swing.JRadioButton PocoTiempo;
    private javax.swing.JButton Registro;
    private javax.swing.JRadioButton Sedentaria;
    private javax.swing.JRadioButton SiAlergia;
    private javax.swing.JRadioButton SiMascotas;
    private javax.swing.JRadioButton SiNinos;
    private javax.swing.JLabel TiempoLibre;
    private javax.swing.JButton Volver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
