/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2;

/**
 *
 * @author Didier
 */
public class Perfil extends javax.swing.JFrame {

    /**
     * Creates new form Perfil
     */
    public Perfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        perfil = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameAsos = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        recomenMasc = new javax.swing.JComboBox<>();
        imagenAsos = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        imagenMascota = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        cerrarSesion = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        recomenMasc1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        recomenMasc2 = new javax.swing.JComboBox<>();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        perfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Mi perfil.");
        perfil.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Asociaciones de adopción:");
        perfil.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        nameAsos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        perfil.add(nameAsos, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 159, 289, 20));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Descubrir Amigos:");
        perfil.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, -1, -1));

        recomenMasc.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        recomenMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recomenMascActionPerformed(evt);
            }
        });
        perfil.add(recomenMasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, 120, -1));
        perfil.add(imagenAsos, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 400, 270));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Recomendación de mascotas:");
        perfil.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        perfil.add(imagenMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 400, 270));

        name.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        perfil.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 48, 289, 19));

        cerrarSesion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cerrarSesion.setText("Cerrar Sesión");
        perfil.add(cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 470, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Nombre:");
        perfil.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 48, -1, -1));

        recomenMasc1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        perfil.add(recomenMasc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 120, 120, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Amigos:");
        perfil.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        recomenMasc2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        perfil.add(recomenMasc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 120, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto2/fondoPerfil.jpeg"))); // NOI18N
        perfil.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 570));

        getContentPane().add(perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recomenMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recomenMascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recomenMascActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel imagenAsos;
    private javax.swing.JLabel imagenMascota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nameAsos;
    private javax.swing.JPanel perfil;
    private javax.swing.JComboBox<String> recomenMasc;
    private javax.swing.JComboBox<String> recomenMasc1;
    private javax.swing.JComboBox<String> recomenMasc2;
    // End of variables declaration//GEN-END:variables
}
